import type {
  User,
  Report,
  Match,
  Subscription,
  Notification,
  DashboardStats,
  Location,
} from "../types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Tawonga Chirwa",
    email: "tawonga@email.com",
    gender: "female",
    age: 26,
    locationId: "l1",
    locationName: "Blantyre",
    status: "active",
    verificationStatus: "verified",
    plan: "premium_monthly",
    photos: [
      { id: "p1", url: "", isMain: true, uploadedAt: "2025-04-12T10:00:00Z" },
      { id: "p2", url: "", isMain: false, uploadedAt: "2025-04-12T10:01:00Z" },
      { id: "p3", url: "", isMain: false, uploadedAt: "2025-04-12T10:02:00Z" },
    ],
    documents: [],
    joinedAt: "2025-04-12T10:00:00Z",
    lastActiveAt: new Date().toISOString(),
    isOnline: true,
    totalMatches: 4,
    messagesSent: 142,
    reportsFiled: 0,
    reportsAgainst: 0,
    initials: "TC",
    avatarColor: "linear-gradient(135deg,#c026d3,#7c3aed)",
  },
  {
    id: "u2",
    name: "Mphatso Nkosi",
    email: "mphatso@email.com",
    gender: "male",
    age: 30,
    locationId: "l2",
    locationName: "Lilongwe",
    status: "active",
    verificationStatus: "unverified",
    plan: "free",
    photos: [
      { id: "p4", url: "", isMain: true, uploadedAt: "2025-03-08T10:00:00Z" },
    ],
    documents: [],
    joinedAt: "2025-03-08T10:00:00Z",
    lastActiveAt: "2025-05-01T14:00:00Z",
    isOnline: false,
    totalMatches: 1,
    messagesSent: 23,
    reportsFiled: 0,
    reportsAgainst: 0,
    initials: "MN",
    avatarColor: "linear-gradient(135deg,#0d9488,#0284c7)",
  },
  {
    id: "u3",
    name: "Bright Kamanga",
    email: "bright@email.com",
    gender: "male",
    age: 28,
    locationId: "l3",
    locationName: "Zomba",
    status: "active",
    verificationStatus: "verified",
    plan: "premium_monthly",
    photos: [
      { id: "p5", url: "", isMain: true, uploadedAt: "2025-02-21T10:00:00Z" },
    ],
    documents: [],
    joinedAt: "2025-02-21T10:00:00Z",
    lastActiveAt: new Date().toISOString(),
    isOnline: true,
    totalMatches: 2,
    messagesSent: 78,
    reportsFiled: 0,
    reportsAgainst: 0,
    initials: "BK",
    avatarColor: "linear-gradient(135deg,#f59e0b,#ef4444)",
  },
  {
    id: "u4",
    name: "John Doe",
    email: "john@email.com",
    gender: "male",
    age: 33,
    locationId: "l4",
    locationName: "Mzuzu",
    status: "banned",
    verificationStatus: "rejected",
    plan: "free",
    photos: [],
    documents: [],
    joinedAt: "2025-01-03T10:00:00Z",
    lastActiveAt: "2025-03-15T10:00:00Z",
    isOnline: false,
    totalMatches: 0,
    messagesSent: 5,
    reportsFiled: 0,
    reportsAgainst: 2,
    initials: "JD",
    avatarColor: "linear-gradient(135deg,#6b7280,#9ca3af)",
  },
  {
    id: "u5",
    name: "Fatima Salim",
    email: "fatima@email.com",
    gender: "female",
    age: 24,
    locationId: "l1",
    locationName: "Blantyre",
    status: "active",
    verificationStatus: "pending",
    plan: "free",
    photos: [
      { id: "p6", url: "", isMain: true, uploadedAt: "2025-04-28T10:00:00Z" },
      { id: "p7", url: "", isMain: false, uploadedAt: "2025-04-28T10:01:00Z" },
      { id: "p8", url: "", isMain: false, uploadedAt: "2025-04-28T10:02:00Z" },
    ],
    documents: [
      {
        id: "d1",
        type: "national_id",
        fileUrl: "",
        filename: "national_id_front.jpg",
        fileSizeMb: 1.2,
        uploadedAt: "2025-04-28T10:00:00Z",
      },
      {
        id: "d2",
        type: "national_id",
        fileUrl: "",
        filename: "national_id_back.jpg",
        fileSizeMb: 0.9,
        uploadedAt: "2025-04-28T10:01:00Z",
      },
    ],
    joinedAt: "2025-04-28T10:00:00Z",
    lastActiveAt: "2025-04-30T10:00:00Z",
    isOnline: false,
    totalMatches: 0,
    messagesSent: 0,
    reportsFiled: 0,
    reportsAgainst: 0,
    initials: "FS",
    avatarColor: "linear-gradient(135deg,#8b5cf6,#ec4899)",
  },
  {
    id: "u6",
    name: "Grace Nyirenda",
    email: "grace@email.com",
    gender: "female",
    age: 29,
    locationId: "l2",
    locationName: "Lilongwe",
    status: "active",
    verificationStatus: "pending",
    plan: "free",
    photos: [
      { id: "p9", url: "", isMain: true, uploadedAt: "2025-04-28T10:00:00Z" },
      { id: "p10", url: "", isMain: false, uploadedAt: "2025-04-28T10:01:00Z" },
    ],
    documents: [
      {
        id: "d3",
        type: "passport",
        fileUrl: "",
        filename: "passport.jpg",
        fileSizeMb: 2.1,
        uploadedAt: "2025-04-28T10:00:00Z",
      },
    ],
    joinedAt: "2025-04-10T10:00:00Z",
    lastActiveAt: "2025-04-29T10:00:00Z",
    isOnline: false,
    totalMatches: 0,
    messagesSent: 3,
    reportsFiled: 0,
    reportsAgainst: 0,
    initials: "GN",
    avatarColor: "linear-gradient(135deg,#14b8a6,#22c55e)",
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: "r1",
    reporterId: "u1",
    reporterName: "Chisomo Mwale",
    reporterInitials: "CM",
    reporterAvatarColor: "linear-gradient(135deg,#c026d3,#7c3aed)",
    reportedUserId: "u4",
    reportedUserName: "User #4821",
    type: "inappropriate_photo",
    description:
      "This user uploaded photos that are clearly not appropriate for a dating platform.",
    status: "pending",
    adminNotes: null,
    resolvedAt: null,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "r2",
    reporterId: "u2",
    reporterName: "Thandiwe Kamwendo",
    reporterInitials: "TK",
    reporterAvatarColor: "linear-gradient(135deg,#14b8a6,#22c55e)",
    reportedUserId: "u4",
    reportedUserName: "User #2209",
    type: "harassment",
    description: "Sending repeated offensive messages after I unmatched.",
    status: "pending",
    adminNotes: null,
    resolvedAt: null,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: "r3",
    reporterId: "u3",
    reporterName: "Blessings Ngwira",
    reporterInitials: "BN",
    reporterAvatarColor: "linear-gradient(135deg,#f59e0b,#ef4444)",
    reportedUserId: "u4",
    reportedUserName: "User #3317",
    type: "fake_profile",
    description:
      "All photos look stolen from social media. Profile info inconsistent.",
    status: "resolved",
    adminNotes: "User banned after investigation.",
    resolvedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: "m1",
    user1Id: "u1",
    user1Name: "Tawonga Chirwa",
    user1Initials: "TC",
    user1AvatarColor: "linear-gradient(135deg,#c026d3,#7c3aed)",
    user2Id: "u2",
    user2Name: "Mphatso Nkosi",
    user2Initials: "MN",
    user2AvatarColor: "linear-gradient(135deg,#0d9488,#0284c7)",
    type: "automatic",
    status: "active",
    locationName: "Lilongwe",
    createdAt: new Date(Date.now() - 3 * 60000).toISOString(),
    dissolvedAt: null,
  },
  {
    id: "m2",
    user1Id: "u3",
    user1Name: "Chimwemwe Dube",
    user1Initials: "CD",
    user1AvatarColor: "linear-gradient(135deg,#10b981,#3b82f6)",
    user2Id: "u5",
    user2Name: "Ruth Msiska",
    user2Initials: "RM",
    user2AvatarColor: "linear-gradient(135deg,#f97316,#eab308)",
    type: "manual",
    status: "active",
    locationName: "Zomba",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    dissolvedAt: null,
  },
  {
    id: "m3",
    user1Id: "u6",
    user1Name: "Joseph Mwanza",
    user1Initials: "JM",
    user1AvatarColor: "linear-gradient(135deg,#6366f1,#8b5cf6)",
    user2Id: "u2",
    user2Name: "Grace Nyirenda",
    user2Initials: "GN",
    user2AvatarColor: "linear-gradient(135deg,#14b8a6,#22c55e)",
    type: "automatic",
    status: "active",
    locationName: "Mzuzu",
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    dissolvedAt: null,
  },
];

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "s1",
    userId: "u1",
    userName: "Tawonga Chirwa",
    userInitials: "TC",
    userAvatarColor: "linear-gradient(135deg,#c026d3,#7c3aed)",
    plan: "premium_monthly",
    startedAt: "2025-04-01T00:00:00Z",
    expiresAt: "2025-05-01T00:00:00Z",
    isActive: true,
    paymentStatus: "paid",
  },
  {
    id: "s2",
    userId: "u3",
    userName: "Bright Kamanga",
    userInitials: "BK",
    userAvatarColor: "linear-gradient(135deg,#f59e0b,#ef4444)",
    plan: "premium_monthly",
    startedAt: "2025-03-15T00:00:00Z",
    expiresAt: "2025-04-15T00:00:00Z",
    isActive: false,
    paymentStatus: "expired",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "Welcome to AnzathuConnect!",
    body: "Find your meaningful connection today. Complete your profile to get started.",
    audience: "all",
    sentAt: "2025-04-30T10:00:00Z",
    deliveredCount: 24600,
    status: "sent",
  },
  {
    id: "n2",
    title: "Upgrade to Premium",
    body: "See who liked you, unlimited matches and more. Upgrade today!",
    audience: "free",
    sentAt: "2025-04-20T10:00:00Z",
    deliveredCount: 20198,
    status: "sent",
  },
];

export const MOCK_LOCATIONS: Location[] = [
  {
    id: "l1",
    name: "Blantyre",
    type: "district",
    parentId: "c1",
    parentName: "Malawi",
    isActive: true,
    userCount: 9200,
  },
  {
    id: "l2",
    name: "Lilongwe",
    type: "district",
    parentId: "c1",
    parentName: "Malawi",
    isActive: true,
    userCount: 8100,
  },
  {
    id: "l3",
    name: "Zomba",
    type: "district",
    parentId: "c1",
    parentName: "Malawi",
    isActive: true,
    userCount: 4100,
  },
  {
    id: "l4",
    name: "Mzuzu",
    type: "district",
    parentId: "c1",
    parentName: "Malawi",
    isActive: true,
    userCount: 3231,
  },
  {
    id: "t1",
    name: "Limbe",
    type: "town",
    parentId: "l1",
    parentName: "Blantyre",
    isActive: true,
  },
  {
    id: "t2",
    name: "Chilomoni",
    type: "town",
    parentId: "l1",
    parentName: "Blantyre",
    isActive: true,
  },
  {
    id: "t3",
    name: "Area 25",
    type: "town",
    parentId: "l2",
    parentName: "Lilongwe",
    isActive: true,
  },
  {
    id: "t4",
    name: "Kanengo",
    type: "town",
    parentId: "l2",
    parentName: "Lilongwe",
    isActive: true,
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalUsers: 24631,
  totalMatches: 8247,
  onlineNow: 1842,
  pendingReports: 23,
  pendingVerifications: 7,
  newSignupsToday: 247,
  newSignupsWeek: 1284,
  newSignupsMonth: 4891,
  premiumUsers: 4433,
  premiumConversionRate: 18,
  reportsResolved: 7908,
  reportsResolvedRate: 96,
  weeklySignups: [148, 195, 172, 231, 210, 261, 247],
};
